# Generated by Django 5.2.11 on 2026-07-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='attendance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
