# Generated by Django 5.2.11 on 2026-07-26 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gymmembership',
            unique_together={('user', 'gym', 'role')},
        ),
    ]
