# Generated by Django 5.2.11 on 2026-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_alter_gymmembership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
